### ISSUE TITLE
Make the code platform independent

### ISSUE THREAD

**Issue by SubhrajitPrusty** [jajodiaraghav/Snake#15]
Use platform independent paths.
Currently, throws error in Linux as path to Assets is Windows specific.
Use the `os` module.

**Comment by jajodiaraghav** [comment]
Nice catch @SubhrajitPrusty 
Would you like to work on this issue?

**Comment by AshisPadhi** [comment]
i would like to work on that issue @jajodiaraghav @SubhrajitPrusty

**Comment by SubhrajitPrusty** [comment]
@akp1881997 sure. @jajodiaraghav Let him work on this.

**Comment by AshisPadhi** [comment]
i have fixed this issue #16 @jajodiaraghav  @SubhrajitPrusty
