### ISSUE TITLE
sound in game

### ISSUE THREAD

**Issue by AkshJain99** [jajodiaraghav/Snake#23]
there should be a sound in game

**Comment by jajodiaraghav** [comment]
We already have sound in the game. What exactly are you looking for?

**Comment by vinaykrishna64** [comment]
@Aksh12345  Do you mean ingame music?

**Comment by AkshJain99** [comment]
Yes sir I mean there should be some music while game starts and ends

On 7 Dec 2017 11:03 pm, "vinay krishna" <notifications@github.com> wrote:

[image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
for Automatic Cleanup! (notifications@github.com) Add cleanup rule
<https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3DgbkCRdF1dsBQTcfRCTz38Hj%252Fn7LVq3cfj6sFV%252B6%252BBM8%253D%26token%3DvTrFga6jHywgNS6YZuJiWXgSqU9T93%252Bf1sxrao4SOCU05ILeQd413r%252FXHf%252BCI0ZdViDB%252F%252Bbi9G3PGNPt8LF1I6g%252FVmwX6cmJDPm%252BhkUEjXheRtCcl7c01uBQQGrKJEIV3%252FEBLY%252FQsMH53aSRXWhatg%253D%253D&tc_serial=34879182719&tc_rand=1485680466&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
| More info
<http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=34879182719&tc_rand=1485680466&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>

@Aksh12345 <https://github.com/aksh12345> Do you mean ingame music?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jajodiaraghav/Snake/issues/23#issuecomment-350038133>,
or mute the thread

**Comment by vinaykrishna64** [comment]
I have requested a PR solving this
