### ISSUE TITLE
Missing function argument

### ISSUE THREAD

**Issue by GeoZac** [jajodiaraghav/Snake#47]
https://github.com/jajodiaraghav/Snake/blob/5d4aacd31748e4acf27c4c613ee2db1b0ec7b299/main.py#L50 takes a string argument,but such a argument is missing in https://github.com/jajodiaraghav/Snake/blob/5d4aacd31748e4acf27c4c613ee2db1b0ec7b299/main.py#L310 
and moreover I'm not able to reach the code

**Comment by athulp01** [comment]
did you pull the updated branch?

**Comment by GeoZac** [comment]
It's permalinked  and only one branch exists

**Comment by GeoZac** [comment]
Passing a string at https://github.com/jajodiaraghav/Snake/blob/5d4aacd31748e4acf27c4c613ee2db1b0ec7b299/main.py#L310 or initialising a default argument at https://github.com/jajodiaraghav/Snake/blob/5d4aacd31748e4acf27c4c613ee2db1b0ec7b299/main.py#L50 can solve the issue

**Comment by jajodiaraghav** [comment]
Please create a PR in case you are aware of the fix

**Comment by GeoZac** [comment]
I need a default string,what I used was

**Comment by jajodiaraghav** [comment]
Do not close the issue when you submit a PR. Issues gets closed on only after the PR gets merged.
