### ISSUE TITLE
Keep the speed constant

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/Snake#6]
Currently, keeping the arrow key pressed would increase the speed of the snake. We should prevent this action. Additionally, a hotkey "Shift+Arrow" should be used to manually increase the speed during gameplay.

**Comment by AK-007** [comment]
I am working on it.

**Comment by CaptainDaVinci** [comment]
I think this is fixed now, isn't it?

**Comment by jajodiaraghav** [comment]
Yes. Thanks @CaptainDaVinci
